### ISSUE TITLE
Cant login on teams-cli

### ISSUE THREAD

**Issue by JavierMachucaA** [fossteams/teams-cli#5]
I install and login with teams-token repo[1], but cant init teams-cli when I start program with go run ./ [2]
[1]
![image](https://user-images.githubusercontent.com/29420681/171652454-fc73cddb-3d7b-4b42-97a9-1ee5be50c0d2.png)

[2]
![image](https://user-images.githubusercontent.com/29420681/171652039-cb0f35d3-7140-4949-a484-c6769a30b4e3.png)

**Comment by ScriptingDad** [comment]
I second this.  Just gave it a shot.

**Comment by denysvitali** [comment]
This is due to a new added field in the `User` model. I've added this field and updated the library here.

The client here was using an outdated version of `teams-api`, which in turn didn't have the `debugDisallowUnknownFields` flag (which is now off by default).

It was decided to fail hard on new fields / renamed fields as this would help further in the debugging - for sure it's not a great user experience though :D 

If another field gets added by Microsoft, the CLI shouldn't fail anymore.
